# Generated by Django 4.0.1 on 2022-01-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_rename_auther_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rental_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
